### ISSUE TITLE
was it malicious.?

### ISSUE THREAD

**Issue by oraby55** [sp0oOk/8ball-pool-cheat#1]
i know the cheat and i was hesitant to use it since my antivirus showed its malicious. or is it a false positive

**Comment by sp0oOk** [comment]
From what I can see no, there was multiple stages leading up to execution. However, this version was not in any way malicious. Cannot say anything about later versions.

**Comment by oraby55** [comment]
Im sorry but when you reversed engineer it were you able to use the premium version? if so ,is it possible that you share it.

**Comment by sp0oOk** [comment]
I only had the version available from github, so presumably no, if you are able to obtain it though add me on discord and I'll go through it (username: 9j2)

**Comment by oraby55** [comment]
Ight i dmed u
